name: Find Support MA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # 北京时间 12:00

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run support MA search
        run: python find_support_ma.py --ma_min 20 --ma_max 300 --ma_step 5 --recover_window 60 --min_touches 2
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: support-ma-results
          path: support_ma_results
